### ISSUE TITLE
Jaling Expansion Map Conflict

### ISSUE THREAD

**Issue by yabo75** [ArcheMagArch/endless-nova#1]
I have been following your very impressive (and intricate) work, and I admire your dedication to such a large project. When I installed it, though, I noted that your map directly overlaps the system map of the [Jaling Expansion](https://github.com/RizkyPramudyaCJ/Jaling-Expansion). Because of this, I essentially added +3000 to the X axis to each planet for your mod to give them a non-overlapping home in my own game, but, figured you may appreciate the file to mitigate the overlap in a future commit, but just, fair warning- The decimal points  for positions under 3k may about 50% inaccurate as I got lazy when I got down into the 2900/2800 range after 350+ system location modifications. The whole number should be correct, though. 

In retrospect, he has a LOT less systems, but, he hasn't updated in a while, so, I didn't think to mod his because I intended to share the "detangled" file to help anyone else who had this problem. 

Keep up the great work! 

[map systems.txt](https://github.com/ArcheMagArch/endless-nova/files/2279961/map.systems.txt)

**Comment by ArcheMagArch** [comment]
Thank you for your interest in my project and your contribution! I agree that it needs more space based on it's proximity to the Ember Wastes as well as any conflicts with future Endless Sky expansions. I'll investigate and implement this.

**Comment by ArcheMagArch** [comment]
There we go, this shouldn't be a problem anymore. Or ever again. I had to manually change the location of every label, which makes me appreciate all the edits you did. Thanks. That took a while. It might be a pain to scroll between the two universes, but that's the price of traveling between alternate realities.

![image](https://user-images.githubusercontent.com/40445738/44131905-a20802d0-a01b-11e8-938c-396d8977e82e.png)
